### ISSUE TITLE
Dependency issues 

### ISSUE THREAD

**Issue by aaronkl** [aws/fmeval#170]
Hi all,
I am trying to install the package on my Mac via `pip install fmeval`, but installation fails because of problems with the tokenizers package. It seems that the rust compilation fails. Is there a way to install with out this dependency?

**Comment by malhotra18** [comment]
The issue has been encountered earlier in Mac M1 chip systems. Could you please try to update rust once? Try following the below steps: 

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh
rustup install 1.72.1
rustup default 1.72.1-aarch64-apple-darwin
rustup toolchain remove stable-aarch64-apple-darwin
rm -rf $HOME/.rustup/toolchains/stable-aarch64-apple-darwin
mv $HOME/.rustup/toolchains/1.72.1-aarch64-apple-darwin $HOME/.rustup/toolchains/stable-aarch64-apple-darwin
```
