### ISSUE TITLE
Evaluation Algorithm for Recommendations

### ISSUE THREAD

**Issue by mccartni-aws** [aws/fmeval#199]
Thanks for the great work. 

I'm working with a customer that is looking to use LLMs for recommendation. We are proactively working on some evaluation metrics/algorithms. 

Are there any plans to add any evaluation algorithms for recommendations? 
I am happy to contribute and submit a PR for this, if not.

**Comment by danielezhu** [comment]
Hi @mccartni-aws, thanks for reaching out!

We aren't actively working on developing any new metrics/algorithms at the moment. However, I am working on some major changes to the internals of the library which will make implementing new metrics/algorithms significantly easier. These changes should be released by 3/28, so if you aren't in a rush, it will be a more pleasant experience for you (in terms of contributing to our codebase) if you wait until then.

**Comment by mccartni-aws** [comment]
Hey @danielezhu 
That's fine, I can wait until then 🦖

**Comment by mccartni-aws** [comment]
Hi @danielezhu 
Do you have any idea of when this upcoming release is coming?

**Comment by danielezhu** [comment]
We released [v1.0.0](https://github.com/aws/fmeval/releases/tag/v1.0.0) last week!
