### ISSUE TITLE
[Bug] Radar plot using plotly not displaying

### ISSUE THREAD

**Issue by jcassiojr** [aws/fmeval#316]
Running model-comparison.ipynb I realized the radar plot is not displaying.
I fixed by adding the following code:
```
import plotly.io as pio
pio.renderers.default = 'notebook'
```

**Comment by xiaoyi-cheng** [comment]
Thank you for reporting this bug.
I tried the model-comparison.ipynb notebook on my dev env, with the fix that you proposed, I still face the same issue.
Can you help explain more?

**Comment by shrestha-bikash** [comment]
@jcassiojr can you please provide update on this PR whether the issue has been fixed or not?
